[tool.poetry]
name = "tiktok-downloader"
version = "0.1.0"
description = "A simple Python script that uses yt_dlp to download TikTok videos or playlists."
authors = ["akeeme <your_email@example.com>"]
readme = "README.md"
packages = [{ include = "tiktok-downloader" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
yt-dlp = "2024.12.23"
flask = "^2.3.0"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
# Add any dev dependencies like testing tools here (optional)

[project]
name = "tiktok-downloader"
version = "0.1.0"
description = "A simple Python script that uses yt_dlp to download TikTok videos or playlists."
authors = [
    { name = "akeeme", email = "akeemeblack@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.9,<4.0"
dependencies = [
    "yt-dlp (==2024.12.23)",
    "flask (>=2.3.0,<3.0.0)",
    "gunicorn (>=20.0.0,<21.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
